replicaCount: 1

image:
  pullPolicy: IfNotPresent
  repository: gcr.io/google-samples/microservices-demo/frontend
  tag: v0.1.3

service:
  type: ClusterIP
  NodePort: 30001
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
  hosts:
    - host: front.84.252.143.215.nip.io

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
