apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: AllClusterPodsRO
  namespace: prometheus
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bind-AllClusterPodsRO-bind
  namespace: prometheus
subjects:
  - kind: Group
    name: system:serviceaccounts:prometheus
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: AllClusterPodsRO
  apiGroup: rbac.authorization.k8s.io
