apiVersion: apps/v1
kind: Deployment
metadata:
  name: otus-nginx
  labels:
    app: otus-nginx
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: otus-nginx
  template:
    metadata:
      labels:
        app: otus-nginx
    spec:
      containers:
        - name: otus-nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
