apiVersion: v1
kind: Service
metadata:
  name: otus-nginx
  labels:
    app: otus-nginx
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: otus-nginx
