apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-exporter
  namespace: otus-nginx
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: nginx-exporter
endpoints:
  - port: http