expose:
  type: ingress
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt-staging
      cert-manager.io/acme-challenge-type: http01
    hosts:
      core: harbor.84.252.143.215.nip.io
  tls:
    secret:
      secretName: harbor.84.252.143.215.nip.io
externalURL: https://harbor.84.252.143.215.nip.io
notary:
  enabled: false